### ISSUE TITLE
Support for `require`

### ISSUE THREAD

**Issue by anonimitoraf** [jamesdiacono/Replete#2]
```
tmp_a = require('./tmp-a');
^

ReferenceError: require is not defined
    at eval (eval at <anonymous> (eval at <anonymous> (evalmachine.<anonymous>:20:5)), <anonymous>:1:1)
    at eval (eval at <anonymous> (evalmachine.<anonymous>:20:5), <anonymous>:20:19)
    at evalmachine.<anonymous>:20:5
    at Script.runInThisContext (node:vm:129:12)
    at Object.runInThisContext (node:vm:305:38)
    at file:///home/anonimito/work/open-source/Replete/cmdl/node_padawan.js:33:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

What would it take to support `require`?

**Comment by jamesdiacono** [comment]
When Node.js was first released, JavaScript did not have a module system. There were many ad hoc module systems that people had devised, and Node.js invented their own. Since 2015, JavaScript has had modules baked into the language. All of the major runtimes support it, so there is no longer any need for ad hoc solutions. You still see plenty of legacy Node.js code which uses a global `require` function, but this code is not portable and does not lend itself to static analysis.

Replete uses static analysis extensively. And more importantly, Replete is designed for the future, not the past. If you need to use a legacy script file which uses `require`, and you are unable to rewrite it as a module, it is easy enough to turn it into a module by using a tool like [esbuild](https://github.com/evanw/esbuild).

**Comment by anonimitoraf** [comment]
Ah fair enough. Yeah I agree, but unfortunately, adapting legacy enterprise codebases accordingly isn't usually feasible.

I wonder if there's a way to transform code on-the-fly before it gets to replete?

**Comment by anonimitoraf** [comment]
Oh, it seems like I misunderstood you. Are you saying that esbuild can do this on-the-fly transformation before the code gets to Replete?

**Comment by diachedelic** [comment]
I imagine so. But I am not sure how you will determine which files should be bundled and which should not.

**Comment by anonimitoraf** [comment]
Right. Yeah ok, I don't think it's worth the effort in doing this. :sweat_smile:
