### ISSUE TITLE
Bug with locator?

### ISSUE THREAD

**Issue by anonimitoraf** [jamesdiacono/Replete#4]
`COMMAND {"platform":"node","source":"function cube(x) {return x * x * x;}","locator":"/home/me/file-1.js"}`
`RESULT {"type":"evaluation","string":"[Function: $cube]"}`
Algood

`COMMAND {"platform":"node","source":"cube(3);","locator":"/home/me/file-2.js"}`
`RESULT {"type":"evaluation","string":"27"}`
Should this not complain that `cube` is not defined?

**Comment by jamesdiacono** [comment]
The "locator" property is used to resolve imports found in the "source" property, rather than to partition evaluations into separate contexts.

I understand that all identifiers in Clojure are namespaced, but JavaScript has no such feature, so Replete shares a single context for each environment. This has its own advantages. I have found it handy to do exactly what you do in your example, which is to evaluate a function and use it in another buffer. I have not found this to cause bugs in practice.

**Comment by anonimitoraf** [comment]
Ah, thanks for clearing that up. Fair enough, misconception/mis-assumption on my part. 

Although, since I'm planning to also support the evaluation of whole files, I'll probably implement this separation for completeness. I might maintain a divergent fork of Replete to implement such features.

**Comment by jamesdiacono** [comment]
To implement this, take a look at command_repl.js and browser_repl.js. Instead of creating a single padawan per REPL, you will have to create multiple.

But I'd like to understand your concern. The sharing of context is actually less risky when evaluating whole files. For example, if you evaluate the file
```
let apple;
const orange = "yum";
```
the `apple` and `orange` identifiers are set to `undefined` before the above two lines are evaluated. This means that any existing values in `apple` or `orange` can not possibly interfere. In contrast, running the fragment
```
console.log(apple, orange);
```
_will_ make use of whatever values were previously stored in `apple` and `orange`.

**Comment by jamesdiacono** [comment]
Just to clarify, evaluating

```
console.log(orange);
let orange = "yum";
```

will always log `undefined`, because each top level identifier declared by a script is erased from the scope before evaluation begins.

**Comment by anonimitoraf** [comment]
Right, so I guess what I'm going for here is:
Running the entrypoint file (e.g. `node index.js`) (which in turn evaluate all the `require`d files) should be the same as if you were to evaluate each line of code from `index.js`

**Comment by jamesdiacono** [comment]
Could you please expand on that with some examples?

**Comment by anonimitoraf** [comment]
Ah sorry, so basically, in the scenarios you described, getting `apple` and `orange` as `undefined` is actually the right behavior, I think.

Scenario I'm thinking of:
```
// module-a.js
function f(x) {
  return x * 2;
}

function g(x) {
  return x * 3;
}

// index.js
import * as module_a from './module-a';

f(42);
```

If you run this traditionally, it would give you an error saying that `f` is not defined. But with Replete, it wouldn't, right?

Also, about Clojure namespaces, yep, everything has a namespace, but I see Clojure namespaces analogous to Javascript file paths. Everything in JS has a file path (I guess maybe excluding some internals).

So I'd like to honour the separation of contexts that way. I think a tool that allows REPL-driven development in JS is **revolutionary** so it'd be great if we/I/you could create something complete. (The community thinks hot-reloading is magic but it's really, nothing, compared to being able to evaluate forms on-demand)

**Comment by jamesdiacono** [comment]
When you evaluate an `import` statement, Replete does not evaluate the imported module. Rather, the `import` statement is rewritten as an `import` function with a URL as its argument. Within the padawan, this `import` function is executed prior to evaluation of your script, and Replete serves the module's source code via HTTP. The runtime handles the evaluation of the module's source. This means that the internals of a module are isolated from the REPL's scope, as they should be.

The benefit to this approach is encapsulation and speed. The downside is that imported modules are cached by the runtime. My solution is to restart Replete whenever this becomes a problem, which is bearable because it only takes half a second.

I think you will find that the code you posted will throw an exception when evaluated in Replete, unless you have explicitly evaluated the function `f` declaration beforehand.

I can not see a clear benefit in evaluating files within their own context. Can you? Because this feature would have a cost.

**Comment by anonimitoraf** [comment]
> I think you will find that the code you posted will throw an exception when evaluated in Replete, unless you have explicitly evaluated the function f declaration beforehand.

I get an error when I execute `import * as module_a from './module-a';` 
```
TypeError: (intermediate value).resolve is not a function
    at Object.locate (file:///home/anonimito/work/open-source/Replete/replete.js:118:28)
    at file:///home/anonimito/work/open-source/Replete/command_repl.js:141:53
    at Array.map (<anonymous>)
    at prepare_for_evaluation (file:///home/anonimito/work/open-source/Replete/command_repl.js:139:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
undefined:1
```
but I assumed that this was a bug and assumed that the behavior is intended to be: Eval `module-a.js`
So this error is expected?

> I can not see a clear benefit in evaluating files within their own context. Can you?
I guess, at the moment, it's still not clear to me how evaluating your code via Replete (imagine evaluating each block of code one by one for all your files) differs from just running `node index.js`

**Comment by anonimitoraf** [comment]
> The downside is that imported modules are cached by the runtime. My solution is to restart Replete whenever this becomes a problem, which is bearable because it only takes half a second.

Hmm, no way to invalidate the cache? Also, restarting a REPL is somewhat an anti-pattern, isn't it?

**Comment by jamesdiacono** [comment]
> I get an error when I execute import * as module_a from './module-a';

Don't forget to run replete.js with the `import.meta.resolve` feature turned on.

```
node --experimental-import-meta-resolve /path/to/replete.js
```

> Hmm, no way to invalidate the cache? Also, restarting a REPL is somewhat an anti-pattern, isn't it?

None of the major runtimes provide a way to invalidate the module cache. I think it stems from the fact that JavaScript modules can be stateful. A module is evaluated only wunce by the runtime, and its exportations are shared by every importing module. Introducing multiple instances of a module into a running program can cause unexpected behaviour when they expect to exist as a singleton. If you only use modules with "pure" exportations, this problem goes away.

Fortunately, Replete serves modules to the runtimes via HTTP, and the runtimes interpret the URL as the cache key. This means that the cache of individual modules can be invalidated when their source changes. Simply append a query string containing the module file's hash to every locator produced by the "locator" capability. Strip it off again in the "read" capability.

```
capabilities.locate("./apple.js", "/fruit/orange.js");
-> "/fruit/apple.js?b1946ac92492d2347c6235b4d2611184
```

> I guess, at the moment, it's still not clear to me how evaluating your code via Replete (imagine evaluating each block of code one by one for all your files) differs from just running node index.js. So I don't know how to answer this yet.

It is quicker and easier to run a program in Replete than it is to swap to a terminal and construct a command. But much more importantly, Replete uses your capability functions. This gives you total control over how the source is interpreted.

**Comment by jamesdiacono** [comment]
I have been thinking about this isolation between files. It seems like it might be important for some programmers. But I think this feature should exist in the text editor plugin, not Replete. This allows Replete's interface to remain simple and complete.

If this feature was built into Replete, then Replete would have to be informed whenever a text editor buffer was opened or closed. This is because padawans are not free: each padawan (and there is wun for Node.js, Deno and the browser) takes up about 15MB of memory. Hence, unused padawans must be destroyed when no longer required. Replete would need a chattier messaging protocol, with messages like "open buffer" and "close buffer". This would couple the plugin more tightly with Replete, imposing an extra burden on plugin implementors. Not to mention extra complexity within Replete.

The solution is for the plugin to maintain a replete.js process for each buffer which is currently open.

```
┌──────────────────────────────────────────────────┐
│                                                  │
│                   Text editor                    │
│                                                  │
│                                                  │
│    ┌───────────────┐        ┌───────────────┐    │
│    │               │        │               │    │
│    │  Buffer for   │        │  Buffer for   │    │
│    │  module_a.js  │        │  module_b.js  │    │
│    │               │        │               │    │
│    └───────┬───────┘        └────────┬──────┘    │
│            │                         │           │
│            │                         │           │
└────────────┼─────────────────────────┼───────────┘
             │                         │
             │                         │
             │                         │
             │                         │
    ┌────────▼───────┐        ┌────────▼───────┐
    │                │        │                │
    │  replete.js    │        │  replete.js    │
    │  Node process  │        │  Node process  │
    │                │        │                │
    └┬─────┬──────┬──┘        └┬─────┬──────┬──┘
     │     │      │            │     │      │
 ┌───▼┐ ┌──▼─┐ ┌──▼────┐   ┌───▼┐ ┌──▼─┐ ┌──▼────┐
 │Node│ │Deno│ │Browser│   │Node│ │Deno│ │Browser│
 │REPL│ │REPL│ │REPL   │   │REPL│ │REPL│ │REPL   │
 └────┘ └────┘ └───────┘   └────┘ └────┘ └───────┘
```

For this to work, the port numbers used in replete.js would have to be passed as arguments. The plugin would then be able to provide unique port numbers for each replete.js process.

**Comment by jamesdiacono** [comment]
The port numbers are now passed as arguments to replete.js.

**Comment by anonimitoraf** [comment]
Hey @jamesdiacono sorry for the late response. I understand that^ but I've decided I'll just write my own "engine". Thanks for all the help

**Comment by diachedelic** [comment]
No worries Raf, good luck.
